version: "3"
services: 
    ut2k4:
      name: ut2004Server
      dns: 192.168.1.21
      hostname: ut2004Server
      build: .
      ports: 
        - "8888-8899:7777-7788/udp"
        - "8888-8899:7777-7788/tcp"
        - "27900/tcp"
        - "27900/udp"
        - "42292/tcp"
        - "42292/udp"
        - "8075:8075/tcp"